const RailButton = ({ icon: Icon, label, active, onClick, theme, className }) => {
	const isDark = theme.textMain === 'text-white';
	return (
		<button
			onClick={onClick}
			className={`group relative flex flex-col items-center gap-1 w-full py-[10%] rounded-lg focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500/50 transition-all duration-150 active:scale-[0.99] ${
				active
					? 'bg-blue-600 text-white shadow-md shadow-blue-900/20'
					: `${theme.textDim} ${isDark ? 'bg-transparent hover:bg-slate-800/45' : 'bg-transparent hover:bg-slate-100/70'}`
			} ${className || ''}`}
		>
			<Icon className={`w-5 h-5 lg:w-6 lg:h-6 ${active ? 'text-white' : 'group-hover:text-blue-500'}`} />
			<span className="text-[9px] lg:text-[10px] font-semibold">{label}</span>
		</button>
	);
};
const DockButton = ({ icon: Icon, label, color, onClick, theme, className }) => { const dark = theme.textMain === 'text-white'; const colorClasses = { blue: dark ? 'bg-blue-500/12 text-blue-300 border-blue-400/40 hover:bg-blue-500/20' : 'bg-blue-500/10 text-blue-600 border-blue-500/30 hover:bg-blue-500/15', green: dark ? 'bg-green-500/12 text-green-300 border-green-400/40 hover:bg-green-500/20' : 'bg-green-500/10 text-green-600 border-green-500/30 hover:bg-green-500/15', orange: dark ? 'bg-orange-500/12 text-orange-300 border-orange-400/40 hover:bg-orange-500/20' : 'bg-orange-500/10 text-orange-600 border-orange-500/30 hover:bg-orange-500/15', red: dark ? 'bg-red-500/12 text-red-300 border-red-400/40 hover:bg-red-500/20' : 'bg-red-500/10 text-red-600 border-red-500/30 hover:bg-red-500/15', gray: dark ? 'bg-slate-900/90 text-slate-300 border-slate-600 hover:bg-slate-800' : 'bg-white text-slate-600 border-gray-300 hover:bg-gray-50' }; return ( <button onClick={onClick} className={`w-full min-h-[48px] rounded-xl flex flex-col items-center justify-center gap-1 border active:scale-95 transition-all shadow-sm ${colorClasses[color] || colorClasses.gray} ${className || ''}`}><Icon className="w-5 h-5 shrink-0" /><span className="text-[9px] font-black leading-none uppercase truncate max-w-full px-1">{label}</span></button> ); };
const QuickAction = ({ icon: Icon, label, sub, theme, onClick }) => ( <button onClick={onClick} className={`flex flex-col items-start p-3 ${theme.textMain === 'text-white' ? 'bg-slate-800/50 hover:bg-slate-800' : 'bg-gray-50 hover:bg-gray-100'} border ${theme.borderCard} rounded-xl hover:border-blue-500/50 transition-all group`}><div className={`p-2 ${theme.activeItem} rounded-lg mb-2 ${theme.textSub} group-hover:text-blue-500 group-hover:bg-blue-500/10 transition-colors`}><Icon className="w-5 h-5" /></div><span className={`text-sm font-bold ${theme.textMain}`}>{label}</span><span className={`text-[10px] ${theme.textSub}`}>{sub}</span></button> );
const TaskOptionButton = ({ icon: Icon, label, onClick, t }) => ( <button onClick={onClick} className={`p-6 rounded-2xl border ${t.borderCard} ${t.bgCard} hover:border-blue-500 hover:bg-blue-500/5 transition-all flex flex-col items-center gap-4 group`}><div className="w-16 h-16 rounded-full bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center text-blue-600 dark:text-blue-400 group-hover:scale-110 transition-transform"><Icon className="w-8 h-8" /></div><span className={`font-bold text-lg ${t.textMain}`}>{label}</span></button> );
const SettingsTab = ({ label, icon: Icon, active, onClick, theme }) => ( <button onClick={onClick} className={`w-full flex items-center justify-between gap-2 p-3 rounded-xl transition-colors ${active ? 'bg-blue-600 text-white' : theme.textMain}`}><div className="flex items-center gap-3 min-w-0"><Icon className="shrink-0 w-5 h-5" /><span className="text-sm font-medium truncate">{label}</span></div>{active && <ChevronRight className="shrink-0 w-4 h-4" />}</button> );
const SettingInput = ({ label, value, onChange, theme, type = "text" }) => ( <div className="flex flex-col gap-1.5"><label className={`text-[11px] font-bold uppercase ${theme.textSub}`}>{label}</label><input type={type} value={value} onChange={onChange} className={`${theme.bgInput} border ${theme.borderCard} rounded-lg px-4 py-2.5 ${theme.textMain}`} /></div> );
const SettingToggle = ({ label, active, theme }) => ( <div className={`flex items-center justify-between p-4 ${theme.bgInput} border ${theme.borderCard} rounded-xl`}><span className={`font-bold ${theme.textMain}`}>{label}</span><div className={`w-12 h-7 rounded-full p-1 ${active ? 'bg-green-500' : 'bg-slate-400'}`}><div className={`w-5 h-5 rounded-full bg-white shadow-md transform ${active ? 'translate-x-5' : ''}`}></div></div></div> );
const SettingSlider = ({ label, value, min, max, theme }) => ( <div className={`flex flex-col gap-2 p-4 ${theme.bgInput} border ${theme.borderCard} rounded-xl`}><div className="flex justify-between"><span className={`font-bold ${theme.textMain}`}>{label}</span><span className="text-blue-500 font-mono">{value}%</span></div><input type="range" min={min} max={max} defaultValue={value} className="w-full accent-blue-500 h-2 bg-slate-600 rounded-lg" /></div> );
